// Package codegen lowers a checked Teyru program to portable C.
//
// The generated C is compiled to a native executable (optionally through LLVM)
// with no JVM involved: classes become C structs, virtual dispatch becomes a
// vtable, garbage collection is a conservative mark-and-sweep runtime.
package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/LangYa466/Teyru/internal/ast"
	"github.com/LangYa466/Teyru/internal/sema"
	"github.com/LangYa466/Teyru/internal/util"
)

// Emitter produces one C translation unit for a whole program.
type Emitter struct {
	prog        *sema.Program
	types       strings.Builder  // typedefs and struct declarations
	fns         strings.Builder  // forward declarations
	code        *strings.Builder // function bodies
	data        strings.Builder  // globals: strings, class metadata
	strings     map[string]int
	strOrder    []string
	mainCls     *ast.Class
	tmp         int
	indent      int
	thrown      []string
	locals      map[*ast.Var]string
	enumOrdinal string
	patternVars map[*ast.InstanceOf]string
	// matches recorded by primitive type patterns, which test the value
	patternOK map[*ast.InstanceOf]string
	curClass  *ast.Class
	retType   ast.Type // declared result type of the method being emitted
	curLambda *ast.Lambda
	switchID  int
	// static type of the selector of the switch being emitted: a primitive type
	// pattern in a case asks about a box only when the selector is a reference
	switchSel ast.Type
	switchCur int
	// labels attached to the statement being emitted right now; a loop
	// consumes them and turns them into its continue and break targets
	pendingLabels []string
	// continue target of each enclosing loop; a basic `for` is lowered to a
	// while with its update at the end of the body, so an unlabelled
	// continue must jump over the rest of the body to reach that update
	loops []string
	// finally blocks of the try statements being emitted, innermost last; an
	// abrupt exit has to run them before it leaves
	finallys []finFrame
	// nesting depth of each labelled loop, for a labelled break or continue
	labelDepth map[string]int
	// objects that can live on the C stack in the method being emitted
	stackLocals map[*ast.Var]*ast.New
	// what is known about each method's receiver
	leakCache map[*ast.Method]leakState
	// primitive types named by a class literal, whose class objects the emitter
	// synthesizes; filled in while the function bodies are emitted and written
	// out with the rest of the metadata, before them
	primClasses map[ast.PrimKind]bool
}

// finFrame is one try statement whose finally action must still run.
type finFrame struct {
	emit  func() // writes the finally action
	depth int    // len(loops) when the try was entered
	name  string // C name of the frame's exception handler
}

// Emit returns the C source for a program.
func Emit(p *sema.Program) string {
	e := &Emitter{
		prog:        p,
		strings:     map[string]int{},
		locals:      map[*ast.Var]string{},
		leakCache:   map[*ast.Method]leakState{},
		primClasses: map[ast.PrimKind]bool{},
		code:        &strings.Builder{},
	}
	e.run()
	var out strings.Builder
	out.WriteString("/* generated by the Teyru compiler */\n")
	out.WriteString("#include \"tyrt.h\"\n#include <math.h>\n#include <string.h>\n\n")
	out.WriteString(e.types.String())
	out.WriteString(e.fns.String())
	out.WriteString(e.data.String())
	out.WriteString(e.code.String())
	out.WriteString(e.entry())
	return out.String()
}

func (e *Emitter) run() {
	for _, cl := range e.prog.Classes {
		e.declareClass(cl)
	}
	for _, cl := range e.prog.Classes {
		e.emitClassMeta(cl)
	}
	for _, cl := range e.prog.Classes {
		e.emitClassCode(cl)
	}
	// the metadata of the classes a class literal synthesized, now that the
	// bodies that may name them have been emitted
	e.emitPrimClassMeta()
}

// primClassName is the C name of the class a primitive class literal names.
func primClassName(k ast.PrimKind) string {
	return mangle("teyru.prim." + (&ast.PrimType{Kind: k}).String())
}

// emitPrimClassMeta writes the class behind a primitive class literal, such as
// `int.class`. A primitive is not a class in Teyru: no value is ever an
// instance of one, since an int boxes to teyru.Integer, and the program has no
// metadata for it. The literal still has to answer with what javac answers --
// "int", "boolean", "void" -- so the class is synthesized here rather than
// reusing the wrapper class, which would answer "teyru.Integer" and compare
// equal to Integer.class, where Java keeps the two apart.
//
// The struct carries only a name: nothing walks it. Its id is negative, since
// it is not one of the program's classes (that counter starts at zero and the
// runtime never reads the field), and it has no superclass or members, as a
// primitive type has none.
func (e *Emitter) emitPrimClassMeta() {
	for k := ast.Void; k <= ast.Double; k++ {
		if !e.primClasses[k] {
			continue
		}
		fmt.Fprintf(&e.data, "static tyclass cls_%s = {%q, %d, 0, NULL, 0, NULL, 0, NULL, NULL, 0, 0, NULL, 0, NULL, 0, NULL};\n",
			primClassName(k), (&ast.PrimType{Kind: k}).String(), -1-int(k))
	}
}

// ---------------------------------------------------------------- naming

// cname is the C type name of a class.
func cname(cl *ast.Class) string {
	return "C_" + util.Mangle(cl.Full)
}

// mangle is the shared identifier mangler.
func mangle(s string) string { return util.Mangle(s) }

func fnName(cl *ast.Class, m *ast.Method, idx int) string {
	owner := ""
	if cl != nil {
		owner = mangle(cl.Full)
	}
	name := m.Name
	if m.IsCtor {
		// "<init>" mangles to "_init_", which cannot collide with a user method
		name = "<init>"
	}
	if m.Accessor != nil && m.Prop != nil {
		if m.Accessor.IsSet {
			name = "set_" + m.Prop.Name
		} else {
			name = "get_" + m.Prop.Name
		}
	}
	return "M_" + owner + "_" + mangle(name) + "_" + fmt.Sprint(idx)
}

// methodIndex finds the position of m among the same-named methods of its owner.
func methodIndex(m *ast.Method) int {
	if m.Owner == nil {
		return 0
	}
	for i, x := range m.Owner.Methods[m.Name] {
		if x == m {
			return i
		}
	}
	for i, x := range m.Owner.Ctors {
		if x == m {
			return i
		}
	}
	return 0
}

func (e *Emitter) cfunc(m *ast.Method) string {
	if m.External {
		// implemented outside the generated program
		return m.Native
	}
	if m.LLName == "" {
		m.LLName = fnName(m.Owner, m, methodIndex(m))
	}
	return m.LLName
}

// ---------------------------------------------------------------- C types

func (e *Emitter) ctype(t ast.Type) string {
	switch v := t.(type) {
	case nil:
		return "void"
	case *ast.PrimType:
		switch v.Kind {
		case ast.Void:
			return "void"
		case ast.Boolean:
			return "int32_t"
		case ast.Byte:
			return "int8_t"
		case ast.Short:
			return "int16_t"
		case ast.Char:
			return "uint16_t"
		case ast.Int:
			return "int32_t"
		case ast.Long:
			return "int64_t"
		case ast.Float:
			return "float"
		case ast.Double:
			return "double"
		}
		return "int32_t"
	case *ast.ClassType:
		return cname(v.Class) + "*"
	case *ast.ArrayType:
		return "tyarr*"
	case *ast.TypeVarType:
		return e.ctype(e.prog.Erased(v))
	case *ast.WildcardType:
		return "void*"
	case ast.NullType:
		return "void*"
	case ast.ErrorType:
		return "void*"
	}
	return "void*"
}

func (e *Emitter) isRef(t ast.Type) bool { return util.IsRef(t) }

// zero renders the zero value of a C type.
func zeroOf(c string) string {
	switch c {
	case "int32_t", "int16_t", "uint16_t", "int8_t", "int64_t", "float", "double":
		return "0"
	}
	return "NULL"
}

// elemSize returns the byte size of an array element type as a C constant.
func (e *Emitter) elemSize(t ast.Type) string {
	return fmt.Sprint(util.SizeOf(t))
}

func (e *Emitter) isRefElem(t ast.Type) bool { return e.isRef(t) }

// ---------------------------------------------------------------- class decls

func (e *Emitter) declareClass(cl *ast.Class) {
	// the special classes are typedefs of runtime types, and they must be
	// visible before any struct that has a field of that type
	switch cl.Special {
	case "String", "box", "sb":
		e.types.WriteString(e.structOf(cl))
		return
	}
	fmt.Fprintf(&e.types, "typedef struct %s %s;\n", cname(cl), cname(cl))
}

func (e *Emitter) structOf(cl *ast.Class) string {
	switch cl.Special {
	case "String":
		return "typedef tystr " + cname(cl) + ";\n"
	case "sb":
		return "typedef tySB " + cname(cl) + ";\n"
	case "box":
		return "typedef " + boxStruct(cl) + " " + cname(cl) + ";\n"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "struct %s {\n  tyobj obj;\n", cname(cl))
	for _, f := range cl.InstFields {
		fmt.Fprintf(&b, "  %s f_%s;\n", e.ctype(f.Type), mangle(f.Name))
	}
	for _, v := range e.prog.CapturedVars(cl) {
		fmt.Fprintf(&b, "  %s cap_%s;\n", e.ctype(v.Type), mangle(v.Name))
	}
	b.WriteString("};\n")
	return b.String()
}

func (e *Emitter) emitClassMeta(cl *ast.Class) {
	if cl.Special != "String" && cl.Special != "box" && cl.Special != "sb" {
		// special classes were declared with their typedef in the first pass
		e.types.WriteString(e.structOf(cl))
	}
	e.emitStaticFields(cl)
	isIface := cl.IsInterface()
	flags := 0
	if isIface {
		flags |= 1
	}
	if cl.Special == "box" {
		flags |= 4
	}
	sup := "NULL"
	if cl.Super != nil {
		sup = "&cls_" + mangle(cl.Super.Class.Full)
	}
	// vtable
	var vt []string
	for _, m := range cl.VTable {
		vt = append(vt, "(void*)"+e.cfunc(m))
	}
	if len(vt) == 0 {
		vt = []string{"NULL"}
	}
	fmt.Fprintf(&e.data, "static void* vt_%s[%d] = {%s};\n", mangle(cl.Full), len(vt), strings.Join(vt, ", "))
	// interface table
	//
	// Sparse, sorted by selector, and holding only what the class actually
	// implements. It used to be one slot per selector the whole program
	// declares -- one pointer per slot -- so a class paid 4.4 KB of .data no
	// matter how many of them it answered for. Every class the program
	// mentions carries one of these, so a hello world pinned 180 of them,
	// 792 KB, for methods it could not reach. ty_itab scans the few entries
	// a class really has instead of indexing into the whole set.
	sel := e.prog.Selectors
	sels := make([]int, 0, len(cl.Ifaces))
	impls := map[int]string{}
	for _, iface := range e.prog.AllInterfaces(cl) {
		for _, m := range e.prog.InterfaceMethods(iface) {
			if m.Selector < 0 || m.Selector >= sel {
				continue
			}
			if impl := e.prog.Implements(cl, m); impl != nil {
				// later interfaces overwrite earlier ones, as they did when the
				// entry was written into a slot the whole table shared
				if _, seen := impls[m.Selector]; !seen {
					sels = append(sels, m.Selector)
				}
				impls[m.Selector] = "(void*)" + e.cfunc(impl)
			}
		}
	}
	sort.Ints(sels)
	imapName, imapLen := "NULL", 0
	if len(sels) > 0 {
		parts := make([]string, len(sels))
		for i, s := range sels {
			parts[i] = fmt.Sprintf("{%d, %s}", s, impls[s])
		}
		imapName, imapLen = "imap_"+mangle(cl.Full), len(sels)
		fmt.Fprintf(&e.data, "static tymap %s[%d] = {%s};\n", imapName, imapLen, strings.Join(parts, ", "))
	}
	// ifaces list
	var ifs []string
	for _, i := range cl.Ifaces {
		ifs = append(ifs, "&cls_"+mangle(i.Class.Full))
	}
	if len(ifs) == 0 {
		ifs = []string{"NULL"}
	}
	fmt.Fprintf(&e.data, "static tyclass* if_%s[] = {%s};\n", mangle(cl.Full), strings.Join(ifs, ", "))
	// reference field offsets, following the C struct layout with alignment
	var capTypes []ast.Type
	for _, v := range e.prog.CapturedVars(cl) {
		capTypes = append(capTypes, v.Type)
	}
	refOffsets, isize := util.FieldLayout(cl.InstFields, capTypes)
	offs := make([]string, 0, len(refOffsets))
	for _, o := range refOffsets {
		offs = append(offs, fmt.Sprint(o))
	}
	off := isize
	if len(offs) == 0 {
		offs = []string{"0"}
	}
	fmt.Fprintf(&e.data, "static int32_t refs_%s[] = {%s};\n", mangle(cl.Full), strings.Join(offs, ", "))
	clinit := "NULL"
	if cl.ClInit != nil {
		clinit = "(void*)" + e.cfunc(cl.ClInit)
	}
	fmt.Fprintf(&e.data, "static tyclass cls_%s = {%q, %d, %d, %s, %d, if_%s, %d, vt_%s, %s, %d, %d, %s, 0, NULL, %d, refs_%s};\n",
		mangle(cl.Full), cl.Full, cl.ID, flags, sup, len(cl.Ifaces), mangle(cl.Full),
		len(cl.VTable), mangle(cl.Full), clinit, int(off), imapLen, imapName, len(offs), mangle(cl.Full))
	if cl.Outer != nil && cl.Inner {
	}
}

func boxStruct(cl *ast.Class) string {
	switch cl.Name {
	case "Integer":
		return "tyintbox"
	case "Long":
		return "tylongbox"
	case "Double":
		return "tydoublebox"
	case "Float":
		return "tyfloatbox"
	case "Character":
		return "tycharbox"
	case "Boolean":
		return "tyboolbox"
	case "Byte":
		return "tybytebox"
	case "Short":
		return "tyshortbox"
	}
	return "tyintbox"
}

// bindCaptures points the captured variables of an anonymous class at the
// fields its constructor filled, and returns a function restoring the previous
// bindings.
func (e *Emitter) bindCaptures(cl *ast.Class) func() {
	var saved []*ast.Var
	var prev []string
	for _, v := range e.prog.CapturedVars(cl) {
		saved = append(saved, v)
		prev = append(prev, e.locals[v])
		e.locals[v] = "this->cap_" + mangle(v.Name)
	}
	return func() {
		for i, v := range saved {
			e.locals[v] = prev[i]
		}
	}
}

func (e *Emitter) sizeOf(t ast.Type) int64 { return util.SizeOf(t) }

// ---------------------------------------------------------------- methods

func (e *Emitter) emitClassCode(cl *ast.Class) {
	e.emitClInit(cl)
	for _, name := range mangleOrder(cl) {
		for i, m := range cl.Methods[name] {
			e.emitMethod(cl, m, i)
		}
	}
	for i, m := range cl.Ctors {
		e.emitMethod(cl, m, i)
	}
}

func mangleOrder(cl *ast.Class) []string {
	var names []string
	for n := range cl.Methods {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// bodyOf returns the syntax body of a method, if any.
func bodyOf(m *ast.Method) *ast.Block {
	if m.Body != nil {
		return m.Body
	}
	if m.Decl != nil && m.Decl.Body != nil {
		return m.Decl.Body
	}
	if m.Accessor != nil {
		return m.Accessor.Body
	}
	return nil
}

// signature renders the C declaration of a method.
func (e *Emitter) signature(m *ast.Method) string {
	ret := e.ctype(m.Result)
	if m.IsCtor {
		ret = "void"
	}
	var params []string
	if !m.IsStatic() {
		params = append(params, cname(m.Owner)+"* this")
	}
	for i, p := range m.Params {
		params = append(params, fmt.Sprintf("%s a%d", e.ctype(p), i))
	}
	if len(params) == 0 {
		params = append(params, "void")
	}
	return fmt.Sprintf("%s %s(%s)", ret, e.cfunc(m), strings.Join(params, ", "))
}

func (e *Emitter) emitMethod(cl *ast.Class, m *ast.Method, idx int) {
	if m.SynthKind == "lambda" || m.SynthKind == "lambda-ctor" {
		e.emitLambdaMethod(cl, m)
		return
	}
	if m.External {
		// a native method is implemented outside this translation unit
		fmt.Fprintf(&e.fns, "%s;\n", e.nativeSignature(m))
		return
	}
	fmt.Fprintf(&e.fns, "static %s;\n", e.signature(m))
	body := bodyOf(m)
	if body == nil && !m.IsCtor && m.SynthKind != "" {
		e.emitSynthetic(cl, m)
		return
	}
	if body == nil && !m.IsCtor && m.Decl != nil {
		e.emitSynthetic(cl, m)
		return
	}
	e.indent = 0
	fmt.Fprintf(e.code, "static %s {\n", e.signature(m))
	e.indent++
	prevClass, prevRet := e.curClass, e.retType
	prevStack := e.stackLocals
	e.curClass = cl
	e.retType = m.Result
	e.stackLocals = e.findStackLocals(body)
	restore := e.bindCaptures(cl)
	defer func() {
		e.curClass, e.retType = prevClass, prevRet
		e.stackLocals = prevStack
		restore()
	}()
	for i, pv := range m.ParamVars {
		e.locals[pv] = fmt.Sprintf("a%d", i)
	}
	if m.IsCtor {
		e.emitCtorBody(cl, m)
	} else if body != nil {
		e.emitBlockInner(body)
	} else {
		// Only reachable for abstract or native methods with no implementation;
		// fail loudly instead of returning an undefined value.
		e.line("ty_unimplemented(%s);\n", e.cstr(cl.Full+"."+m.Name))
	}
	e.indent--
	e.code.WriteString("}\n\n")
}

// ctorCallIndex returns the position of the this()/super() call in a
// constructor body, or -1 when there is none.
func ctorCallIndex(b *ast.Block) int {
	for i, st := range b.Stmts {
		es, ok := st.(*ast.ExprStmt)
		if !ok {
			continue
		}
		if call, ok := es.X.(*ast.Call); ok && call.ThisCtor {
			return i
		}
	}
	return -1
}

// emitCtorBody writes the chained constructor call, field initializers and the
// body. Teyru supports flexible constructor bodies (JEP 513): statements may
// appear before the super()/this() call, and they run first.
func (e *Emitter) emitCtorBody(cl *ast.Class, m *ast.Method) {
	e.line("\n")
	body := bodyOf(m)
	idx := -1
	if body != nil {
		idx = ctorCallIndex(body)
	}
	// 1. prologue: statements before the explicit constructor call
	if idx > 0 {
		for _, st := range body.Stmts[:idx] {
			e.stmt(st)
		}
	}
	// 2. chain to the superclass or the sibling constructor
	switch {
	case m.SynthKind == "anon-ctor" && m.Forward != nil:
		recv := "this"
		if o := m.Forward.Owner; o != nil {
			recv = "(" + cname(o) + "*)this"
		}
		var args []string
		for i := range m.Params {
			args = append(args, fmt.Sprintf("a%d", i))
		}
		call := e.cfunc(m.Forward) + "(" + recv
		if len(args) > 0 {
			call += ", " + strings.Join(args, ", ")
		}
		e.line("%s);\n", call)
	case idx >= 0:
		// the explicit call is emitted with the rest of the body
	case cl.Super == nil || cl.Super.Class == e.prog.Builtins.Object:
		// nothing to chain to
	default:
		if sup := e.findSuperCtor(cl); sup != nil {
			e.line("%s(%s);\n", e.cfunc(sup), e.args("this", nil, sup))
		}
	}
	// captured locals arrive as parameters trailing the forwarded ones
	if m.SynthKind == "anon-ctor" {
		base := 0
		if m.Forward != nil {
			base = len(m.Forward.Params)
		}
		for i, cv := range e.prog.CapturedVars(cl) {
			e.line("this->cap_%s = a%d;\n", mangle(cv.Name), base+i)
		}
	}
	// 3. instance field initializers run after the superclass constructor
	e.emitFieldInits(cl, m)
	// 4. the body itself (including the explicit constructor call, if any)
	if body != nil {
		stmts := body.Stmts
		if idx > 0 {
			stmts = stmts[idx:]
		}
		for _, st := range stmts {
			e.stmt(st)
		}
	}
	if m.Decl != nil && m.Decl.Compact {
		e.emitRecordAssign(cl, m)
		return
	}
	if m.SynthKind == "record-ctor" {
		e.emitRecordAssign(cl, m)
	}
}

func (e *Emitter) emitRecordAssign(cl *ast.Class, m *ast.Method) {
	for _, rc := range cl.Decl.RecordComps {
		f := cl.FieldMap[rc.Name]
		if f == nil {
			continue
		}
		e.line("this->f_%s = a%d;\n", mangle(f.Name), indexOfName(m.ParamNames, rc.Name))
	}
}

func indexOfName(names []string, n string) int {
	for i, x := range names {
		if x == n {
			return i
		}
	}
	return 0
}

// emitFieldInits runs instance field initializers in declaration order.
func (e *Emitter) emitFieldInits(cl *ast.Class, ctor *ast.Method) {
	if cl.Decl == nil {
		return
	}
	// superclass fields are initialized by the super constructor
	for _, mem := range cl.Decl.Members {
		fd, ok := mem.(*ast.FieldDecl)
		if !ok {
			continue
		}
		for _, vd := range fd.Vars {
			if vd.Init == nil || vd.Fld == nil || vd.Fld.Mods.Has(ast.ModStatic) {
				continue
			}
			target := "this->f_" + mangle(vd.Fld.Name)
			e.line("%s = %s;\n", target, e.coerce(e.expr(vd.Init), vd.Init.GetType(), vd.Fld.Type))
		}
	}
	for _, mem := range cl.Decl.Members {
		ib, ok := mem.(*ast.InitBlock)
		if !ok || ib.Static {
			continue
		}
		e.emitBlockInner(ib.Body)
	}
}

func (e *Emitter) findSuperCtor(cl *ast.Class) *ast.Method {
	sup := cl.Super.Class
	for _, c := range sup.Ctors {
		if len(c.Params) == 0 {
			return c
		}
	}
	if len(sup.Ctors) > 0 {
		return sup.Ctors[0]
	}
	return nil
}

// line writes an indented line of generated C.
func (e *Emitter) line(format string, args ...any) {
	for i := 0; i < e.indent; i++ {
		e.code.WriteString("  ")
	}
	fmt.Fprintf(e.code, format, args...)
}

func (e *Emitter) tmpName() string {
	e.tmp++
	return fmt.Sprintf("_t%d", e.tmp)
}

// entry emits main() and the startup sequence.
func (e *Emitter) entry() string {
	var b strings.Builder
	main := e.prog.Main
	b.WriteString("\nint main(int argc, char** argv) {\n  (void)argc; (void)argv;\n  ty_init();\n")
	b.WriteString(e.clinitRefs())
	b.WriteString("  TY_STRING = &cls_" + mangle(e.prog.Builtins.String.Full) + ";\n")
	b.WriteString("  TY_OBJECT = &cls_" + mangle(e.prog.Builtins.Object.Full) + ";\n")
	// the arrays the compiler creates get this class, so `a instanceof Object`,
	// `(Object) a` and `"" + a` behave, and the collector can see that an array's
	// elements are references and trace them
	b.WriteString("  TY_ARRAY = &cls_" + mangle(e.prog.ArrayClass().Full) + ";\n")
	// sorted: iterating the map directly would emit TY_BOX assignments in a
	// different order every run, so two builds of one program would not produce
	// the same C and the output could not be diffed
	boxKinds := make([]int, 0, len(e.prog.Builtins.Boxes))
	for k := range e.prog.Builtins.Boxes {
		boxKinds = append(boxKinds, int(k))
	}
	sort.Ints(boxKinds)
	for _, k := range boxKinds {
		fmt.Fprintf(&b, "  TY_BOX[%d] = &cls_%s;\n", k, mangle(e.prog.Builtins.Boxes[ast.PrimKind(k)].Full))
	}
	for _, pair := range [][2]any{
		{"TY_NPE", e.prog.Builtins.NPE}, {"TY_AIOOBE", e.prog.Builtins.AIOOBE},
		{"TY_ARITH", e.prog.Builtins.Arith}, {"TY_CCE", e.prog.Builtins.CCE},
		{"TY_NEGARR", e.prog.Builtins.NegArr}, {"TY_ASSERT", e.prog.Builtins.Assertion},
		{"TY_ILLARG", e.prog.Builtins.IllArg}, {"TY_ILLSTATE", e.prog.Builtins.IllState},
		{"TY_NOSUCHELEM", e.prog.Builtins.NoSuchElem}, {"TY_UNSUP", e.prog.Builtins.Unsup},
		{"TY_ARRAYSTORE", e.prog.Builtins.ArrayStore},
	} {
		if cl, ok := pair[1].(*ast.Class); ok && cl != nil {
			fmt.Fprintf(&b, "  %s = &cls_%s;\n", pair[0], mangle(cl.Full))
		}
	}
	b.WriteString("  ty_clinit(&cls_" + mangle(e.prog.Builtins.Object.Full) + ");\n")
	// Only the classes that actually have a static initializer are named here.
	// ty_clinit on a class whose whole hierarchy has none is a no-op, but
	// naming it takes the class's address in main, and that single reference
	// keeps the class -- its vtable, its interface table, its methods, and
	// everything it in turn mentions -- alive through link-time optimisation.
	// Taking one address per class pinned the entire standard library into
	// every executable: a hello world built from the same sources was 1.8 MB
	// with 1.4 MB of it interface tables no program could ever reach.
	//
	// The lazy guards the call sites already carry (clinitCall, clinitStmt)
	// are what actually runs an initializer, in Java's on-first-use order.
	seenInit := map[string]bool{}
	for _, cl := range e.prog.Classes {
		if cl.Builtin || seenInit[cname(cl)] || !needsClinit(cl, map[*ast.Class]bool{}) {
			continue
		}
		seenInit[cname(cl)] = true
		fmt.Fprintf(&b, "  ty_clinit(&cls_%s);\n", mangle(cl.Full))
	}
	if main == nil {
		b.WriteString("  return 0;\n}\n")
		return b.String()
	}
	recv := ""
	if !main.IsStatic() {
		// the class is a C struct, so the instance an instance main runs on is
		// its pointer; spelling these without the `*` emitted C that does not
		// compile for a compact file with `void main(String[] args)`
		fmt.Fprintf(&b, "  %s* _main_obj = (%s*)ty_alloc(sizeof(%s));\n", cname(main.Owner), cname(main.Owner), cname(main.Owner))
		fmt.Fprintf(&b, "  _main_obj->obj.cls = &cls_%s;\n", mangle(main.Owner.Full))
		recv = "_main_obj, "
	}
	if len(main.Params) == 1 {
		b.WriteString("  tyarr* _args = ty_array_new(argc > 0 ? argc - 1 : 0, 8);\n")
		b.WriteString("  _args->refs = 1;\n")
		b.WriteString("  for (int _i = 1; _i < argc; _i++) ((void**)_args->data)[_i - 1] = (void*)ty_str_intern(argv[_i]);\n")
		fmt.Fprintf(&b, "  %s(%s_args);\n", e.cfunc(main), recv)
	} else {
		fmt.Fprintf(&b, "  %s(%s);\n", e.cfunc(main), strings.TrimSuffix(recv, ", "))
	}
	b.WriteString("  return 0;\n}\n")
	return b.String()
}

// capture runs fn with a fresh output buffer and returns what it wrote.
func (e *Emitter) capture(fn func()) string {
	old := e.code
	e.code = &strings.Builder{}
	fn()
	s := e.code.String()
	e.code = old
	return s
}
